# Generated by Django 5.2.6 on 2025-09-13 03:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-email_date']},
        ),
        migrations.AlterModelOptions(
            name='emailaccount',
            options={'ordering': ['-date_added']},
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='host',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='port',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='use_ssl',
        ),
        migrations.AddField(
            model_name='email',
            name='bcc',
            field=models.TextField(blank=True, default='', help_text='BCC recipients'),
        ),
        migrations.AddField(
            model_name='email',
            name='cc',
            field=models.TextField(blank=True, default='', help_text='CC recipients'),
        ),
        migrations.AddField(
            model_name='email',
            name='email_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Original email date from headers'),
        ),
        migrations.AddField(
            model_name='email',
            name='has_attachments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='html_body',
            field=models.TextField(blank=True, default='', help_text='HTML version of email body'),
        ),
        migrations.AddField(
            model_name='email',
            name='in_reply_to',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='message_id',
            field=models.CharField(blank=True, default='', help_text='Unique message ID from email server', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='thread_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='auto_sync',
            field=models.BooleanField(default=True, help_text='Automatically sync emails'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='email_address',
            field=models.EmailField(default='example@email.com', help_text='Email address', max_length=254),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='incoming_host',
            field=models.CharField(default='imap.gmail.com', help_text='IMAP/POP3 server host', max_length=100),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='incoming_port',
            field=models.IntegerField(default=993, help_text='IMAP/POP3 server port'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='incoming_use_ssl',
            field=models.BooleanField(default=True, help_text='Use SSL for incoming mail'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='outgoing_host',
            field=models.CharField(default='smtp.gmail.com', help_text='SMTP server host', max_length=100),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='outgoing_port',
            field=models.IntegerField(default=587, help_text='SMTP server port'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='outgoing_use_ssl',
            field=models.BooleanField(default=True, help_text='Use SSL for outgoing mail'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='sync_from_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Start syncing emails from this date'),
        ),
        migrations.AlterField(
            model_name='email',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='crm.emailaccount'),
        ),
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='email',
            name='recipient',
            field=models.TextField(default='recipient@example.com', help_text='Comma-separated list of recipients'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.EmailField(default='sender@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('sent', 'Sent'), ('draft', 'Draft'), ('failed', 'Failed')], default='received', max_length=10),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='name',
            field=models.CharField(default='Untitled Account', help_text='Display name for this account', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='protocol',
            field=models.CharField(choices=[('IMAP', 'IMAP'), ('POP3', 'POP3'), ('SMTP', 'SMTP')], default='IMAP', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='username',
            field=models.CharField(default='username', max_length=100),
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='attachment.txt', max_length=255)),
                ('content_type', models.CharField(default='text/plain', max_length=100)),
                ('size', models.IntegerField(default=0, help_text='Size in bytes')),
                ('file_data', models.BinaryField(default=b'')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.email')),
            ],
        ),
        migrations.CreateModel(
            name='EmailFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inbox', max_length=100)),
                ('folder_type', models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('drafts', 'Drafts'), ('spam', 'Spam'), ('trash', 'Trash'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='crm.emailaccount')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('account', 'name')},
            },
        ),
        migrations.AddField(
            model_name='email',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.emailfolder'),
        ),
    ]
